on:
    push:
    workflow_dispatch: 
  
jobs:
    build_frontend:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
  
        - name: Install dependencies and build the React app
          run: npm install && npm run build
          working-directory: ./frontend
  
        - name: Upload frontend artifact
          uses: actions/upload-artifact@v4
          with:
            name: frontend-artifact
            path: ./frontend/build/*
  
    build_backend:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
  
        - name: Publish .NET app
          run: dotnet publish -c Release --property:PublishDir=publish
          working-directory: ./backend
  
        - name: Upload backend artifact
          uses: actions/upload-artifact@v4
          with:
            name: backend-artifact
            path: ./backend-publish
  
    trigger_cd_pipeline:
      needs: [build_frontend, build_backend]
      runs-on: ubuntu-latest
      steps:
        - name: Trigger CD Pipeline
          run: |
            curl -X POST \
              -H "Authorization: token ${{ secrets.BATMAN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/Neros5/parkndeploy/actions/workflows/cd-pipeline.yml/dispatches \
              -d '{"ref":"main"}'
        - uses: actions/checkout@v3
    
    call_deploy_workflow:    
        needs: [build_frontend, build_backend]
        permissions:
            id-token: write # Require write permission to Fetch an OIDC token (required for federated credential)
        uses: Neros5/parkndeploy/.github/workflows/cd-pipeline.yml@main
        secrets: inherit
        