on: 
    pull_request:
  
permissions:
    id-token: write
  
env: 
    AZURE_RG_NAME: ${{ vars.PROJECT_NAME }}-rg-${{ vars.AZURE_RESOURCE_IDENTIFIER }}
    
jobs:
    build_frontend:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Build the app
          run: npm install && npm run build
          working-directory: ./frontend

        - name: Linting
          run: npm run lint
          working-directory: ./frontend

    build_backend:
        runs-on: ubuntu-latest

        steps:
            - name: Build the app
              run: dotnet build
        
      
  